### ISSUE TITLE
Sometimes api  $.afui.loadContent dont's work.

### ISSUE THREAD

**Issue by zhangkangbin** [01org/appframework#871]
app error :
Uncaught TypeError: from.end(...).run is not 
a functionAFUi.runTransition @ 
af.ui.js:938AFUi.runViewTransition 
@ af.ui.js:1004AFUi.loadDiv 
@ af.ui.js:731AFUi.loadContent @ af.ui.js:649

i  dont's know  ..
.thanks

**Comment by imaffett** [comment]
Can you please post a demo showing this?

Which device/OS are you experiencing this on?

**Comment by junaidmalik09** [comment]
Same problem here. Testing on Chrome browser. I run the function $.afui.loadContent("#main") when the login button is pressed. But instead of loading the panel, it gives the following error in the console. Please refer to the attached image.

![screen shot 2015-06-22 at 7 52 47 am](https://cloud.githubusercontent.com/assets/2422532/8275694/c20303a2-18b3-11e5-9e8c-45718359ee26.png)

**Comment by imaffett** [comment]
@junaidmalik09 - See my reply above - please post a demo that I can try to debug this with.

**Comment by hsw409328** [comment]
same problem! why ? from.end.run is not function . ios and wechat browser can not run!

**Comment by imaffett** [comment]
@hsw409328  Can you post a demo so I can try to debug this?

**Comment by hsw409328** [comment]
the demo templates loginview.html. 
server：apache
dev environment: php 

local test:ios google firefox wechat

**Comment by imaffett** [comment]
This should be resolved now.  Thanks @hsw409328 for pointing me to a page to debug this.

**Comment by bgyhnddr** [comment]
it is a bug...$.afui.loadContent('#store_page2',false,false,undefined,$.afui.activeDiv); will work,
but $.afui.loadContent('#store_page2',true,false,undefined,$.afui.activeDiv); still wrong,the code sucks
