### ISSUE TITLE
panel active not disabled between views

### ISSUE THREAD

**Issue by tahoetomahawk** [01org/appframework#873]
When calling loadContent between views, the last active panel in the view stays active. There will be 2 active panels.
The panel that does not deactivate never will become deactive when transitioning between pages.

This happens by clicking a footer link <a href="#somepage".. or by using $.afui.loadContent

**Comment by seekchange** [comment]
This was an issue posted before, and I don't think it was ever resolved. However, I did link a comment to an existing pull request posted in April #850 .

the update to af.ui.js adds to the runTransition function and removes the active class if found. it works, but it requires a transition to be set when calling the panels, and not sure if it's the best solution.

**Comment by tahoetomahawk** [comment]
Just added the code.. works great. Thanks so much!

**Comment by tahoetomahawk** [comment]
The side effect is that it hides the background panel when calling a panel within a modal view. Not a big deal though.. I will look into fixing that in a bit

**Comment by imaffett** [comment]
@seekchange  @tahoetomahawk  - can either of you put up demo's showing the bug and how it's resovled with that pull request/  I'll be happy to merge it.

**Comment by tahoetomahawk** [comment]
I used the pull request code as a workaround. It's not quite a resolution
but it gets the job done for now.
Let me know if you still need a pull request, we can put together a sample.

**Comment by imaffett** [comment]
@tahoetomahawk - I'm fine accepting the pull request that is there.  I've just been asking for demos/tests to show the error and that it has been resolved.

**Comment by tahoetomahawk** [comment]
I will include a page with multiple views that shows the issue later this
evening.

**Comment by manish-stack** [comment]
@tahoetomahawk : Please upload your solution. I have tried code from #850  but problem is still there. 
@imaffett : Can you please look in to this bug as this is pending from a long time & we are not able to migrate our AF2.2 apps to AF3 just because of this issue. Thanks.

**Comment by imaffett** [comment]
@manish-stack - no one has given me demos/tests/etc

**Comment by tahoetomahawk** [comment]
Hi guys,
I haven't uploaded tests. The work around did not work completely, I found
another issue with it. The on panel load gets triggered, but never the
unload. It looks like the bug happens with transitioning between views, not
panels.
Everything seems to work fine within the same view, but using multiple
views things start to break.
The way that headers and footers are defined at the view level forced me to
have to create multiple views. I'm redesigning my UI and creating my own
Footer I can use on certain panels so I can put everything into the same
view.

**Comment by jdinse** [comment]
Folks, this is really a huge problem we ran into. However, after including these lines from the pull request that @tahoetomahawk mentioned (where were removed in this request, for whatever reason???) at the beginning of `runTransition()` in  `appframework.ui.js` at line  1218, it works:
```javascript
        	if (typeof previous !== "undefined" && previous !== null) {
                if(previous.find) {
                    setTimeout(function(){
                        previous.find(".active").removeClass("active");
                    },500);
                }
            }
```

**Comment by imaffett** [comment]
@jdinse I appreciate it's a huge problem but look at my previous comments. Not one person has given me a demo to test against.  All people say is "it doesn't work fix it".

If this fixes your case, open up a pull request and I'll merge it, but you need a demo/test to show it working.

**Comment by tahoetomahawk** [comment]
Jay, that work around was not sufficient as the panelunload was not being
called when transitioning from 1 view to another. If you don't need
panelload or panelunload then you should be fine.

**Comment by jdinse** [comment]
@tahoetomahawk I found out that it is caused by the fifth Parameter (anchor) in function loadContent(). It changes the current view to what the anchor belongs to for the transition. Therefore it tries to unload the wrong view. Look at lines 1014 ff. in function loadDiv():

            //check current view
            var currentView;
            if(anchor){
                currentView=this.findViewTarget(anchor);
            }
            else
                currentView=this.findViewTarget(this.activeDiv);

So the workaround for me was to not use these fifth parameter right now.

**Comment by tahoetomahawk** [comment]
Good find, thanks!!
